collect_components!(
    groups: {
        ability: [
            projectile,
            straight,
            parallel,
            fan,
            radial,
            lifetime,
            pierce,
            growing,
            damage_payload,
            dash,
            orbiting,
            falling,
            find_nearest_enemy,
            follow_caster,
            destroy_enemy_projectiles,
            boomerang,
            melee_strike,
        ],
        common: [
            size,
            collider,
            sprite,
            health,
            dynamic_body,
            spawn_ability,
            visual,
            jump_walk_animation,
            squish_walk_animation,
            shadow,
        ],
        mob: [
            move_toward,
            keep_distance,
            use_abilities,
            when_near,
            when_found_target,
            after_time,
            lunge_movement,
        ],
        player: [
            keyboard_movement,
            player_input,
        ],
        trigger: [
            on_found,
            on_collision,
            on_area,
            on_expire,
            on_death,
        ],
    }
);
